// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/mp/broadcast/[id].tsx";
import * as $5 from "./routes/mp/broadcast/_layout.tsx";
import * as $6 from "./routes/mp/broadcast/index.tsx";
import * as $$0 from "./islands/BroadcastCard.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/mp/broadcast/[id].tsx": $4,
    "./routes/mp/broadcast/_layout.tsx": $5,
    "./routes/mp/broadcast/index.tsx": $6,
  },
  islands: {
    "./islands/BroadcastCard.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
